python train_T5.py \
    --train_batch_size 32 \
    --epochs 5 \
    --lr 2e-5 \
    --mixed_precision fp16 \
    --t5_size "small" \
    --style_noise 0.0 \
    --label_noise 0.1 \
    --style_enc "MLP" \
    --vae_path "blowing-up-groundhogs/emuru_vae" \
    --report_to "wandb" \
    --wandb_entity "emuru" \
    --wandb_project_name "ours_t5_small" \
    --wandb_log_interval_steps 100