python train_T5.py \
    --train_batch_size 8 \
    --epochs 5 \
    --lr 1e-5 \
    --mixed_precision fp16 \
    --t5_size "large" \
    --style_noise 0.0 \
    --label_noise 0.1 \
    --teacher_p 1.0 \
    --teacher_w 1.0 \
    --style_enc "full" \
    --max_width 768 \
    --vae_path "blowing-up-groundhogs/emuru_vae" \
    --report_to "wandb" \
    --wandb_entity "emuru" \
    --wandb_project_name "ours_t5_large" \
    --wandb_log_interval_steps 100